### ISSUE TITLE
Subclass implementation of onDismiss

### ISSUE THREAD

**Issue by bensheldon** [bogardon/GGFullscreenImageViewController#1]
I'd like to add some custom behavior that gets triggered at the same time as `onDismiss` but it keeps crashing with random errors/crashes in RubyMotion if I try to implement it in a subclass. e.g.

``` ruby
class DetailController < GGFullScreenImageViewController
  def onDismiss
    super
    # do something
  end
end
```

What am I doing wrong?

**Comment by bogardon** [comment]
@bensheldon what are you doing in `# do something`? What if I add an ivar like `completionBlock` to `GGFullscreenImageViewController`? btw I think the S isn't capitalized in "screen".

**Comment by bensheldon** [comment]
On `# do something` I want to change some properties on `imageView`. Basically, I change some properties on `imageView` when the the view appears (speifically, change the contentMode). This is my full intended implementation:

``` ruby
class DetailController < GGFullscreenImageViewController

  # this method works great
  def viewWillAppear(animated)
    super

    imageView.contentMode = UIViewContentModeScaleAspectFit
    # replace the low-res image with a hi-res image and set the low-res to be the placeholder
    imageView.setImageWithURL NSURL.URLWithString(shirt['image_full_url']),
      placeholderImage: imageView.image
  end

  # this method doesn't work
  def onDismiss
    super

     imageView.contentMode = UIViewContentModeScaleAspectFill
  end
end
```

Adding a ivar completion block would be awesome. Mostly I'm just not sure why trying to subclass that particular method doesn't work :-( But I'll take any implementation that let's it work.
